# ======================================
# Stage-1 DeepMoleNet (FS1=6 targets, FS3=7 targets)
# ======================================

common:
  dataset:
    species: [H, C, N, O, F, P, S, Cl, Br, I]
    node_input_dim: 41
    edge_input_dim: 54
    aux_ele_dim: 260
    transforms:
      complete: true
      distance: { norm: false }
    split: { train_ratio: 0.8, seed: 666, shuffle: true }

  acsf:
    r_cut: 6.0
    g2_params: [[1, 1], [1, 2], [1, 3]]
    g4_params: [[1, 1, 1], [1, 2, 1], [1, 1, -1], [1, 2, -1]]

  model:
    hidden_dim: 200
    message_passing_steps: 6
    set2set_steps: 12
    out_aux_dim: 260         

  train:
    device: auto
    epochs: 400
    batch_size: 16
    num_workers: 4
    optimizer: { name: Adam, lr: 1.0e-5, weight_decay: 0.0 }
    scheduler:
      warmup: { enable: true, multiplier: 10.0, total_epoch: 10 }
      cosine_anneal: { enable: true, t_max: 400 }
    log: { print_every: 50, save_best_after_epoch: 300 }

  loss:
    main: L1
    aux: L1
    aux_lambda: 32
    standardize_main_targets: true

  reproducibility:
    torch_seed: 42
    numpy_seed: 42
    python_hash_seed: 0

profiles:

  fs1:   # ------ 6 targets ------
    paths:
      dev_sdf_dir: ./data-bin/raw/dev/sdf
      dev_target_csv: ./data-bin/raw/dev/dev_target.csv
      test_sdf_dir: ./data-bin/raw/test/sdf
      ckpt_best: ./data-bin/models/FS1/DeepMoleNet_best_state_dict.pth
      ckpt_last: ./data-bin/models/FS1/DeepMoleNet_last_state_dict.pth
      out_pred_csv: ./results/predictions/FS1/Predicted_values.csv
    model:
      out_main_dim: 6
    targets:
      columns: [strDipole, strAnisoPolar,	strHarmFreq1,	strHarmFreq2,	strHarmFreq3,	strZeroPointEner]

  fs3:   # ------ 7 targets ------
    paths:
      dev_sdf_dir: ./data-bin/raw/dev/sdf
      dev_target_csv: ./data-bin/raw/dev/dev_target.csv
      test_sdf_dir: ./data-bin/raw/test/sdf
      ckpt_best: ./data-bin/models/FS3/DeepMoleNet_best_state_dict.pth
      ckpt_last: ./data-bin/models/FS3/DeepMoleNet_last_state_dict.pth
      out_pred_csv: ./results/predictions/FS3/Predicted_values.csv
    model:
      out_main_dim: 7
    targets:
      columns: [strvdWGlobalMin,	strvdWGlobalMax,	strvdWTotalVar,	strvdWMinimaNum,	strvdWMaximaNum,	strvdWMinimaSum, strvdWMaximaSum]
